//카드생성 api /9-1/cards api 호출 POST
### 
POST https://sp-taskify-api.vercel.app/9-1/cards HTTP/1.1
Host: localhost:3000
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDY0NCwidGVhbUlkIjoiOS0xIiwiaWF0IjoxNzI5NDMzMjg2LCJpc3MiOiJzcC10YXNraWZ5In0.0Dec1cdKrGKitbfetQTq0Lnw4cCvfQzkOrsGs5kqTDo

{
  "assigneeUserId": 4644,
  "dashboardId": 120009,
  "columnId": 40630,
  "title": "커비",
  "description": "설명",
  "dueDate": "2024-10-30 11:59",
  "tags": [
    "핑크"
  ],
  "imageUrl": "https://via.placeholder.com/30"
}